#!/bin/bash

####
#   Copyright 2019 Bradyn Poulsen
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
####

OPENSSL_VERSION=$(echo $DOCKER_TAG | cut -f1 -d-)
OPENSSL_FIPS_VERSION=$(echo $DOCKER_TAG | cut -f2 -d-)

echo "Target OpenSSL Version: $OPENSSL_VERSION"
echo "Target OpenSSL FIPS Version: $OPENSSL_FIPS_VERSION"

docker build \
    --build-arg OPENSSL_VERSION=${OPENSSL_VERSION} \
    --build-arg OPENSSL_FIPS_VERSION=${OPENSSL_FIPS_VERSION} \
    -f $DOCKERFILE_PATH \
    -t $IMAGE_NAME \
    .