#!/bin/bash
docker build \
    --build-arg OPENSSL_VERSION=$(echo $DOCKER_TAG | cut -f1 -d-) \
    --build-arg OPENSSL_FIPS_VERSION=$(echo $DOCKER_TAG | cut -f2 -d-) \
    -f $DOCKERFILE_PATH \
    -t $IMAGE_NAME \
    .